{
  "name": "calendar_events_api",
  "description": "Správa Google Kalendáře přes proxy API (načítání, přidávání, úprava, mazání událostí)",
  "schema_version": "v1",
  "functions": [
    {
      "name": "get_events",
      "description": "Načte události z konkrétního Google kalendáře přes proxy API",
      "parameters": {
        "type": "object",
        "properties": {
          "calendarId": {
            "type": "string",
            "description": "Google Calendar ID"
          },
          "timeMin": {
            "type": "string",
            "description": "Počáteční čas v ISO 8601 formátu"
          },
          "timeMax": {
            "type": "string",
            "description": "Koncový čas v ISO 8601 formátu"
          },
          "pageToken": {
            "type": "string",
            "description": "Token pro stránkování výsledků (volitelné)"
          }
        },
        "required": ["calendarId"]
      },
      "request": {
        "method": "GET",
        "url": "https://slawinski-calendar-proxy.vercel.app/api/events",
        "query": {
          "calendarId": "{calendarId}",
          "timeMin": "{timeMin}",
          "timeMax": "{timeMax}",
          "pageToken": "{pageToken}"
        }
      }
    },
    {
      "name": "create_event",
      "description": "Vytvoří novou událost v Google kalendáři",
      "parameters": {
        "type": "object",
        "properties": {
          "calendarId": {
            "type": "string",
            "description": "Google Calendar ID"
          },
          "summary": { "type": "string", "description": "Název události" },
          "description": { "type": "string" },
          "location": { "type": "string" },
          "start": { "type": "string", "description": "Start v ISO formátu" },
          "end": { "type": "string", "description": "Konec v ISO formátu" },
          "allDay": { "type": "boolean" },
          "date": { "type": "string", "description": "Datum YYYY-MM-DD (pro allDay)" },
          "attendees": { "type": "array", "items": { "type": "object" } },
          "reminders": { "type": "object" },
          "colorId": { "type": "string" },
          "visibility": { "type": "string" },
          "conference": { "type": "object" },
          "status": { "type": "string" }
        },
        "required": ["calendarId", "summary", "start", "end"]
      },
      "request": {
        "method": "POST",
        "url": "https://slawinski-calendar-proxy.vercel.app/api/events",
        "body": {
          "calendarId": "{calendarId}",
          "summary": "{summary}",
          "description": "{description}",
          "location": "{location}",
          "start": "{start}",
          "end": "{end}",
          "allDay": "{allDay}",
          "date": "{date}",
          "attendees": "{attendees}",
          "reminders": "{reminders}",
          "colorId": "{colorId}",
          "visibility": "{visibility}",
          "conference": "{conference}",
          "status": "{status}"
        }
      }
    },
    {
      "name": "update_event",
      "description": "Aktualizuje existující událost v Google kalendáři",
      "parameters": {
        "type": "object",
        "properties": {
          "calendarId": { "type": "string" },
          "eventId": { "type": "string" },
          "summary": { "type": "string" },
          "description": { "type": "string" },
          "location": { "type": "string" },
          "start": { "type": "string" },
          "end": { "type": "string" },
          "allDay": { "type": "boolean" },
          "date": { "type": "string" },
          "attendees": { "type": "array", "items": { "type": "object" } },
          "reminders": { "type": "object" },
          "colorId": { "type": "string" },
          "visibility": { "type": "string" },
          "conference": { "type": "object" },
          "status": { "type": "string" }
        },
        "required": ["calendarId", "eventId"]
      },
      "request": {
        "method": "PATCH",
        "url": "https://slawinski-calendar-proxy.vercel.app/api/events",
        "body": {
          "calendarId": "{calendarId}",
          "eventId": "{eventId}",
          "summary": "{summary}",
          "description": "{description}",
          "location": "{location}",
          "start": "{start}",
          "end": "{end}",
          "allDay": "{allDay}",
          "date": "{date}",
          "attendees": "{attendees}",
          "reminders": "{reminders}",
          "colorId": "{colorId}",
          "visibility": "{visibility}",
          "conference": "{conference}",
          "status": "{status}"
        }
      }
    },
    {
      "name": "delete_event",
      "description": "Smaže událost z Google kalendáře",
      "parameters": {
        "type": "object",
        "properties": {
          "calendarId": { "type": "string" },
          "eventId": { "type": "string" }
        },
        "required": ["calendarId", "eventId"]
      },
      "request": {
        "method": "DELETE",
        "url": "https://slawinski-calendar-proxy.vercel.app/api/events",
        "query": {
          "calendarId": "{calendarId}",
          "eventId": "{eventId}"
        }
      }
    }
  ]
}
