openapi: 3.0.3
info:
  title: Calendar Proxy (Slawinski via Vercel)
  version: 1.0.0
servers:
  - url: https://slawinski-calendar-proxy.vercel.app
paths:
  /:
    get:
      operationId: list
      parameters:
        - in: query
          name: op
          required: true
          schema:
            type: string
        - in: query
          name: key
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
